name: my first ci/cd pipeline
on:
    push: 
        branches: [ "main" ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Clone the code
            uses: actions/checkout@v4
          - name: Build images
            run: docker build -t matts20002-spec/cicd-portfolio .
          - name: docker login
            uses: docker/login-action@v3
            with:
              username: matts20002-spec
              password: ${{ secrets.DOCKER_PASS}}
          - name: Push images
            run: docker push matts20002-spec/cicd-portfolio
         