name: CI/CD BUILD IMAGES TO AWS ECR
on:
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]
jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: scan with trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          format: 'table'   
          exit-code: '1'
          severity: 'CRITICAL,HIGH,'
      - name: Set up Docker Build
        run: docker build -t 422032869125.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
      - name: scan docker image with trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
            image-ref: '422032869125.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest'
            format: 'table'
            exit-code: '1'
            severity: 'CRITICAL,HIGH,'
            ignore-unfixed: true

      #- name: Log in to Amazon ECR
       # uses: aws-actions/amazon-ecr-login@v1

      #- name: Build and push Docker image
               # env:
               #ECR_REPOSITORY: my-ecr-repo
                #AWS_REGION: us-east-1
                #run: |
                # Build the Docker image
                #docker build -t $IMAGE_NAME .

                # Tag the Docker image for ECR
                #docker tag $IMAGE_NAME:latest $ECR_REPOSITORY:$IMAGE_NAME

                # Push the Docker image to ECR
                #docker push $ECR_REPOSITORY:$IMAGE_NAME 